version: "3"
services:     
  postgres: 
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - diploma
   
  cassandra-master:
    image: cassandra:latest
    container_name: cassandra-master
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=localhost  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra:/var/lib/cassandra:rw
    ports: 
      - 7000:7000
      - 9042:9042
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - diploma
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Проброс порта для доступа к MongoDB с хоста
    volumes:
      - mongo:/data/db  # Монтирование локальной папки для хранения данных
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Задание имени пользователя администратора
      MONGO_INITDB_ROOT_PASSWORD: example  # Задание пароля администратора
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - diploma
        
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
      - 5672:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - diploma    
   
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - diploma
      
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - diploma
      
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - diploma
   
  gate:
    build:
        context: ./Gate
        dockerfile: ./Gate/Dockerfile
    container_name: gate
    environment:
      HOST: rabbitmq
    links:
      - rabbitmq
    ports:
      - "55551:55551"
      - "55552:55552"
      - "55553:55553/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - diploma 
   
volumes:
  pgdata:
    driver: local
  cassandra:
    driver: local
  mongo:
    driver: local
  rabbitmq:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  redis_data:
    driver: local
networks:
  diploma:
    external: true